[package]
name = "starknet_foundation"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.3.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.12.0" }

[dev-dependencies]
cairo_test = ">=2.3.0"

[[target.starknet-contract]] 